project_name: kroki-cli

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    binary: kroki
    main: ./cmd/kroki/
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: yuzutech
    name: kroki-cli
  draft: true
