name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - name: Installer linter (golangci)
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}
      env:
        GOLANGCI_LINT_VERSION: '1.46.2'
    - name: Get dependencies
      run: go mod vendor
      env:
        GO111MODULE: 'on' 
    - name: Test
      run: make test
    - name: Lint
      run: make lint
    - name: Build
      run: |
        curl -sL https://git.io/goreleaser | head -n -2 | bash
        tar -xf /tmp/goreleaser.tar.gz -C $(go env GOPATH)/bin
        goreleaser --snapshot --skip-sign
